src/Entity/Concours.php
<?php

namespace App\Entity;

use App\Repository\ConcoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConcoursRepository::class)
 */
class Concours
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="blob")
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbViews = 0 ;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="concours")
     */
    private $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getContent()
    {
        if($this->content) {
            rewind($this->content);
            return stream_get_contents($this->content);
        }
        return null;
    }

    public function setContent($content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getNbViews(): ?int
    {
        return $this->nbViews;
    }

    public function setNbViews(int $nbViews): self
    {
        $this->nbViews = $nbViews;

        return $this;
    }

    public function incrementNbViews()
    {
        $this->nbViews++;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setConcours($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getConcours() === $this) {
                $commentaire->setConcours(null);
            }
        }

        return $this;
    }
}

src/Entity/Promosport.php
<?php

namespace App\Entity;

use App\Repository\PromosportRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PromosportRepository::class)
 */
class Promosport
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="blob")
     * @Assert\NotBlank(message="Please enter a content.")
     */
    private $content;


    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getContent()
    {
        if($this->content) {
            rewind($this->content);
            return stream_get_contents($this->content);
        }
        return null;
    }

    public function setContent($content): self
    {
        $this->content = $content;

        return $this;
    }



    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }


}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity ;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @UniqueEntity(
 *     fields = {"username"},
 *     message="le username existe déjà"
 * )
 * @Vich\Uploadable()
 */

class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;


    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="Image")
     */
    private $imageFile;

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile)
        {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles ;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="utilisateur")
     */
    private $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles()
    {
        return [$this->roles];
    }

    public function setRoles(?string $roles) :self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt()
    {

    }

    public function eraseCredentials()
    {

    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUtilisateur() === $this) {
                $commentaire->setUtilisateur(null);
            }
        }

        return $this;
    }


}

src/Form/ConcoursType.php
<?php

namespace App\Form;

use App\Entity\Concours;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConcoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content',CKEditorType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Concours::class,
        ]);
    }
}

src/Controller/ConcoursController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Concours;
use App\Form\CommentaireType;
use App\Form\ConcoursType;
use App\Repository\CommentaireRepository;
use App\Repository\ConcoursRepository;
use App\Repository\PromosportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ConcoursController extends AbstractController
{
    /**
     * @Route("/Dashboard/concours", name="Dashboard_concours")
     */
    public function index_back(ConcoursRepository $repository): Response
    {
        $concours = $repository->findAll();
        return $this->render('concours/index.html.twig', [
            "concours" => $concours
        ]);
    }

    /**
     * @Route("/Dashboard/concours/ajouter", name="ajouter_concours")
     * @Route("/Dashboard/concours/modifier/{id}", name="modifier_concours")
     */
    public function Ajouter_modifier(Concours $concours = null, Request $request)
    {
        $modif = false;
        if (!$concours) {
            $concours = new Concours();
            $modif = true;
        }
        $form = $this->createForm(ConcoursType::class, $concours);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $concours->setDate(new \DateTime("now"));
            $em->persist($concours);
            $em->flush();
            $this->addFlash('success', "L'action a ete effectué");
            return $this->redirectToRoute('Dashboard_concours');
        }
        return $this->render('concours/New_concours.html.twig', [
            "form" => $form->createView(),
            "modif" => $modif
        ]);
    }


    /**
     * @Route("/Dashboard/concours/supprimer/{id}", name="supprimer_concours")
     */
    public function delete(Concours $concours)
    {

        $em = $this->getDoctrine()->getManager();
        $em->remove($concours);
        $em->flush();
        $this->addFlash('success', "L'action a ete effectué");
        return $this->redirectToRoute('Dashboard_concours');
    }

    /**
     * @Route("/concours/{id}", name="single_concours")
     */
    public function single_commentaire(Concours $concours, ConcoursRepository $repository, $id, Request $request, CommentaireRepository $commentaireRepository , PromosportRepository $promosportRepository): Response
    {
        $promosport = $promosportRepository->findAll();
        $concours->incrementNbViews();
        $em = $this->getDoctrine()->getManager();
        $em->persist($concours);
        $em->flush();
        $concours = $repository->find($id);

        $commentaires = $commentaireRepository->findby(['concours' => $id]);
        $commentaire_article = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire_article);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $commentaire_article->setUtilisateur($this->getUser());
            $commentaire_article->setConcours($concours);
            $commentaire_article->setCreatedAt(new \DateTime('now'));
            $em = $this->getDoctrine()->getManager();
            $em->persist($commentaire_article);
            $em->flush();
            return $this->redirectToRoute('single_concours',[
                "id"=> $concours->getId()
            ]);
        }
            return $this->render('concours/single_concours.html.twig', [
                "concours" => $concours ,
                "form"=>$form->createView(),
                "commentaires" => $commentaires,
                "promosport"=>$promosport
            ]);
        }


}

templates/concours/New_concours.html.twig
{% extends 'Dashboard.html.twig' %}

{% block title %}Ajouter Concours{% endblock %}

{% block body %}
    <div class="page-header">
        <h3 class="page-title">Ajouter Concours </h3>
    </div>

    {{ form_start(form) }}
    {{ form_row(form.title)}}

    {{ form_row(form.content) }}

    {% if modif %}
        <button class="btn btn-success">Ajouter</button>
    {% else %}
        <button class="btn btn-success">Modifier</button>
    {% endif %}
    {{ form_end(form) }}
{% endblock %}

templates/concours/index.html.twig
{% extends 'dashboard.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <div class="page-header">
        <h3 class="page-title"> Concours </h3>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <a class="nav-link btn btn-success create-new-button"  href="{{ path('ajouter_concours') }}"> + Ajouter nouveau concours </a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Content</th>
                                <th>Created</th>
                                <th>nb_views</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for concours in concours %}
                                <tr>
                                    <td>{{ concours.title }}</td>
                                    <td>{{ concours.getContent | raw }} </td>
                                    <td>{{ concours.date | date('F d, Y') }}</td>
                                    <td>{{ concours.nbViews}}</td>
                                    <td>
                                        <a class="btn btn-primary"  href="{{path('modifier_concours',{'id': concours.id})}}" >modifier</a>
                                    </td>
                                    <td>
                                        <form method="post"  action="{{ path('supprimer_concours' , {'id' : concours.id}) }}" onsubmit="return confirm('Voulez vous supprimer ?')">
                                            <input type="hidden" name="_method" value="SUP">
                                            <input type="hidden" name="_token" value="">
                                            <input type="submit" class="btn btn-danger" value="supprimer">
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/concours/single_concours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promosport{% endblock %}

{% block body %}
    <!-- Breaking News Start -->
    <div class="container-fluid mt-5 mb-3 pt-3">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12">
                    <div class="d-flex justify-content-between">
                        <div class="section-title border-right-0 mb-0" style="width: 180px;">
                            <h4 class="m-0 text-uppercase font-weight-bold">Concours</h4>
                        </div>
                        <div class="owl-carousel tranding-carousel position-relative d-inline-flex align-items-center bg-white border border-left-0"
                             style="width: calc(100% - 180px); padding-right: 100px;">
                            <div class="text-truncate"><a class="text-secondary text-uppercase font-weight-semi-bold" href="">{{ concours.title }}</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breaking News End -->

    <!-- News With Sidebar Start -->
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- News Detail Start -->
                    <div class="position-relative mb-3">
                        <div class="bg-white border border-top-0 p-4">
                            <div class="mb-3">
                                <a class="badge badge-danger text-uppercase font-weight-semi-bold p-2 mr-2"
                                   href="">Article</a>
                                <a class="text-body" href="">{{ concours.date | date('F d, Y') }}</a>
                            </div>
                            <h1 class="mb-3 text-secondary text-uppercase font-weight-bold">{{ concours.title }}</h1>
                            <p>{{  concours.getContent  | raw  }}</p>
                        </div>
                        <div class="d-flex justify-content-between bg-white border border-top-0 p-4">
                            <div class="d-flex align-items-center">
                                <span class="ml-3"><i class="far fa-eye mr-2"></i>{{ concours.nbViews }}</span>
                                <span class="ml-3"><i class="far fa-comment mr-2"></i>123</span>
                            </div>
                        </div>
                    </div>
                    <!-- News Detail End -->

                    <!-- Comment List Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">  Comments</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-4">
                            {% for com in commentaires %}
                                <div class="media mb-4">
                                    <img src="{{ asset('img/user/'~ com.utilisateur.image) }}" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                    <div class="media-body">
                                        <h6>
                                            <a class="text-secondary font-weight-bold">
                                                {{ com.utilisateur.username }}
                                            </a>
                                            <small>
                                                <i> {{ com.createdAt | date('y-m-d h:i:s') }} </i>
                                            </small>
                                        </h6>
                                        <p class="text-dark">
                                            {{ com.contenu }}
                                        </p>
                                        <button class="btn btn-sm btn-outline-secondary">Reply</button>
                                    </div>
                                </div>
                            {% endfor %}
                            {% if app.user %}
                                <div class="section mb-0">
                                    {{ form_start(form)}}
                                    <div class="row">
                                        <div class="col-10">
                                            {{ form_widget(form) }}
                                        </div>
                                        <div class="col-2" style="padding-top: 50px">
                                            <input type="submit" class="btn btn-danger" value="Commenter" >
                                        </div>
                                    </div>
                                    {{ form_end(form) }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <!-- Comment List End -->
                </div>

                <div class="col-lg-4">
                    <!-- Social Follow Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Follow Us</h4>
                        </div>
                        <div class="bg-white border border-top-0 p-3">
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #39569E;">
                                <i class="fab fa-facebook-f text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Fans</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #52AAF4;">
                                <i class="fab fa-twitter text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #0185AE;">
                                <i class="fab fa-linkedin-in text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Connects</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #C8359D;">
                                <i class="fab fa-instagram text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none mb-3" style="background: #DC472E;">
                                <i class="fab fa-youtube text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Subscribers</span>
                            </a>
                            <a href="" class="d-block w-100 text-white text-decoration-none" style="background: #055570;">
                                <i class="fab fa-vimeo-v text-center py-4 mr-3" style="width: 65px; background: rgba(0, 0, 0, .2);"></i>
                                <span class="font-weight-medium">12,345 Followers</span>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->

                    <!-- Ads Start -->
                    <div class="mb-3">
                        <div class="section-title mb-0">
                            <h4 class="m-0 text-uppercase font-weight-bold">Advertisement</h4>
                        </div>
                        <div class="bg-white text-center border border-top-0 p-3">
                            <a href=""><img class="img-fluid" src="img/news-800x500-2.jpg" alt=""></a>
                        </div>
                    </div>
                    <!-- Ads End -->
                </div>
            </div>
        </div>
    </div>
    <!-- News With Sidebar End -->
{% endblock %}